### ISSUE TITLE
Error lein run preprocessing example/input/furelise.png /tmp/furelise.png /tmp/refs.txt

### ISSUE THREAD

**Issue by dayvsonlima** [acieroid/overscore#1]
lein run preprocessing example/input/furelise.png /tmp/furelise.png /tmp/refs.txt
Can't find 'overscore.main' as .class or .clj for lein run: please check the spelling.
Exception in thread "main" java.io.FileNotFoundException: Could not locate overscore/tools/files__init.class or overscore/tools/files.clj on classpath: 
	at clojure.lang.RT.load(RT.java:432)
	at clojure.lang.RT.load(RT.java:400)
	at clojure.core$load$fn__4890.invoke(core.clj:5415)
	at clojure.core$load.doInvoke(core.clj:5414)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5227)
	at clojure.core$load_lib.doInvoke(core.clj:5264)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$load_libs.doInvoke(core.clj:5298)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:605)
	at clojure.core$use.doInvoke(core.clj:5392)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at overscore.recognition.segmentation.segmentation$eval643$loading__4784__auto____644.invoke(segmentation.clj:2)
	at overscore.recognition.segmentation.segmentation$eval643.invoke(segmentation.clj:2)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6501)
	at clojure.lang.Compiler.load(Compiler.java:6952)
	at clojure.lang.RT.loadResourceScript(RT.java:359)
	at clojure.lang.RT.loadResourceScript(RT.java:350)
	at clojure.lang.RT.load(RT.java:429)
	at clojure.lang.RT.load(RT.java:400)
	at clojure.core$load$fn__4890.invoke(core.clj:5415)
	at clojure.core$load.doInvoke(core.clj:5414)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5227)
	at clojure.core$load_lib.doInvoke(core.clj:5264)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$load_libs.doInvoke(core.clj:5298)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:605)
	at clojure.core$use.doInvoke(core.clj:5392)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at overscore.main$eval20$loading__4784__auto____21.invoke(main.clj:1)
	at overscore.main$eval20.invoke(main.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6501)
	at clojure.lang.Compiler.load(Compiler.java:6952)
	at clojure.lang.RT.loadResourceScript(RT.java:359)
	at clojure.lang.RT.loadResourceScript(RT.java:350)
	at clojure.lang.RT.load(RT.java:429)
	at clojure.lang.RT.load(RT.java:400)
	at clojure.core$load$fn__4890.invoke(core.clj:5415)
	at clojure.core$load.doInvoke(core.clj:5414)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5227)
	at clojure.core$load_lib.doInvoke(core.clj:5264)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$load_libs.doInvoke(core.clj:5298)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$require.doInvoke(core.clj:5381)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval5$fn__7.invoke(form-init3111172029045861861.clj:1)
	at user$eval5.invoke(form-init3111172029045861861.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6511)
	at clojure.lang.Compiler.eval(Compiler.java:6501)
	at clojure.lang.Compiler.load(Compiler.java:6952)
	at clojure.lang.Compiler.loadFile(Compiler.java:6912)
	at clojure.main$load_script.invoke(main.clj:283)
	at clojure.main$init_opt.invoke(main.clj:288)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)

**Comment by fangshichao-git** [comment]
Well, I've got this issue too...

**Comment by acieroid** [comment]
Indeed, the tools/files.clj file seems to be missing. I'll have to dig into old hard drives to find it back, if I can't find it in the history of the repo.

**Comment by acieroid** [comment]
The file has been merged into another one. This is now fixed. Thanks for the report to both of you!

**Comment by fangshichao-git** [comment]
Thank you for the reply, but it still doesn't work for me. It reports this:

Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: img% in this context, compiling:(overscore/recognition/segmentation/segmentation.clj:30:50)

In the previous version, I tried deleting the line "use overscore.tools.files" and it got exactly the same error as this version: cannot resolve symbol img%.
Hope you'll fix this :)

**Comment by acieroid** [comment]
This should be fixed with commit 71649b3 :) That was very strange, a space was missing between img and %, but the code still worked for me. Let me know if anything is still failing.

**Comment by fangshichao-git** [comment]
Thanks! It works!
